version: "3.7"


volumes:
   nwp_data:

services:
  postgres-forecast:
    image: postgres:13.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  postgres-pv:
    image: postgres:13.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"

  nwp:
    image: openclimatefix/metoffice_weather_datahub:1.0.10
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-forecast:5432/postgres
      - GIT_PYTHON_REFRESH=quiet
      - LOG_LEVEL=DEBUG
      - SAVE_DIR=data
      - API_KEY=$NWP_API_KEY
      - API_SECRET=$NWP_API_SECRET
    volumes:
      - type: volume
        source: nwp_data
        target: /app/data

  pv:
    image: openclimatefix/pvconsumer:0.0.11
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-pv:5432/postgres
      - LOGLEVEL=DEBUG
      - API_KEY=$PVOUTPUT_API_KEY
      - SYSTEM_ID=$PVOUTPUT_SYSTEM_ID
      - DATA_SERVICE_URL=https://pvoutput.org/
    depends_on:
      - "postgres-pv"

  forecast:
    image: openclimatefix/nowcasting_forecast:0.1.0
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-forecast:5432/postgres
      - GIT_PYTHON_REFRESH=quiet
      - LOG_LEVEL=DEBUG
      - NWP_PATH=./data/latest.netcdf
      - MODEL_NAME=nwp_simple_trained
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    depends_on:
      - "postgres-forecast"
    restart: on-failure
    volumes:
      - type: volume
        source: nwp_data
        target: /app/data


  api:
    image: openclimatefix/nowcasting_api:0.1.18
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres-forecast:5432/postgres
      - GIT_PYTHON_REFRESH=quiet
      - LOG_LEVEL=DEBUG
    depends_on:
      - "postgres-forecast"
      - "postgres-pv"
      - "forecast"
    command: [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80" ]
    ports:
      - 80:80
