name: Local Stack tests
# This work flow runs 'terraform validate' to check there isn't anything obviously wrong

on: [push]

jobs:
  tests:
    name: Local Stack Tests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run
      run: |
        cd local-stack/
        pip install -r tests/requirements.txt

        # start up the stack
        docker-compose up -d

        # run tests
        pytest

        # pull down stack
        docker-compose down
